services:
  shop-nginx:
    image: nginx:stable-alpine
    container_name: shop-nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/cert.pem:/etc/nginx/cert/cert.pem
      - ./cert/key.pem:/etc/nginx/cert/key.pem
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - API_NAME=${API_NAME}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - shop-api
    networks:
      - shop-api-networks

  shop-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - shop-api-db
    networks:
      - shop-api-networks

  shop-api-db:
    image: postgres
    restart: always
    container_name: shop-api-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - shop-api-networks

volumes:
  postgres-data:
    driver: cio
    driver_opts:
      profile: 'POSTGRESQL'

networks:
  shop-api-networks:
    driver: bridge
